### ISSUE TITLE
DoT or DoH

### ISSUE THREAD

**Issue by xiangyu123** [IrineSistiana/mos-chinadns#1]
Will all local_forward and remote_forward support DoT or DoH in the feture?  Some China ServerName line Alidns(223.5.5.5 has support DoT or DoH).   Yes, I know that remote_forward already support DoH.

**Comment by xiangyu123** [comment]
BTW, I really like this project

**Comment by IrineSistiana** [comment]
@xiangyu123 Thanks for your proposal.

As for DoT, no support is currently planned. Because most DoT servers do not support keep-alive(or it's broken). This means that every request requires a full TLS handshake. There will be high latency.

As for DoH support for local server, it will be added in next release.

BTW, is Aliyun DNS has already DoH support? Could you give me some links or docs? I can't find this on their website. O_o

**Comment by xiangyu123** [comment]
@IrineSistiana   I've read the post which URL is "_https://www.ookangzheng.com/dns-collection/_",  and I saw that Alidns already support DoH, but I didn't test it, when I type the URL "https://dns.alidns.com/dns-query", there was a tips:  no 'dns' query parameter found. Also I am looking forward to the next release.

**Comment by xiangyu123** [comment]
Does queryLocal(local_server) also supports ecs ?
